'use client'
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 ./public/models/MLSC-Logo_alpha-final.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function MlscLogo(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/MLSC-Logo_alpha-final.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Curve025">
          <mesh name="Curve025_1" geometry={nodes.Curve025_1.geometry} material={materials['SVGMat.033']} />
          <mesh name="Curve025_2" geometry={nodes.Curve025_2.geometry} material={materials['SVGMat.003']} />
          <mesh name="Curve025_3" geometry={nodes.Curve025_3.geometry} material={materials['SVGMat.028']} />
          <mesh name="Curve025_4" geometry={nodes.Curve025_4.geometry} material={materials['SVGMat.006']} />
          <mesh name="Curve025_5" geometry={nodes.Curve025_5.geometry} material={materials['SVGMat.027']} />
          <mesh name="Curve025_6" geometry={nodes.Curve025_6.geometry} material={materials['SVGMat.029']} />
          <mesh name="Curve025_7" geometry={nodes.Curve025_7.geometry} material={materials['SVGMat.080']} />
          <mesh name="Curve025_8" geometry={nodes.Curve025_8.geometry} material={materials['SVGMat.054']} />
          <mesh name="Curve025_9" geometry={nodes.Curve025_9.geometry} material={materials['SVGMat.058']} />
          <mesh name="Curve025_10" geometry={nodes.Curve025_10.geometry} material={materials['SVGMat.062']} />
          <mesh name="Curve025_11" geometry={nodes.Curve025_11.geometry} material={materials['SVGMat.065']} />
          <mesh name="Curve025_12" geometry={nodes.Curve025_12.geometry} material={materials['SVGMat.072']} />
          <mesh name="Curve025_13" geometry={nodes.Curve025_13.geometry} material={materials['SVGMat.074']} />
          <mesh name="Curve025_14" geometry={nodes.Curve025_14.geometry} material={materials['SVGMat.118']} />
          <mesh name="Curve025_15" geometry={nodes.Curve025_15.geometry} material={materials['SVGMat.084']} />
          <mesh name="Curve025_16" geometry={nodes.Curve025_16.geometry} material={materials['SVGMat.114']} />
          <mesh name="Curve025_17" geometry={nodes.Curve025_17.geometry} material={materials['SVGMat.115']} />
          <mesh name="Curve025_18" geometry={nodes.Curve025_18.geometry} material={materials['SVGMat.113']} />
          <mesh name="Curve025_19" geometry={nodes.Curve025_19.geometry} material={materials['SVGMat.083']} />
          <mesh name="Curve025_20" geometry={nodes.Curve025_20.geometry} material={materials['SVGMat.119']} />
          <mesh name="Curve025_21" geometry={nodes.Curve025_21.geometry} material={materials['SVGMat.082']} />
          <mesh name="Curve025_22" geometry={nodes.Curve025_22.geometry} material={materials['SVGMat.116']} />
          <mesh name="Curve025_23" geometry={nodes.Curve025_23.geometry} material={materials['SVGMat.117']} />
          <mesh name="Curve025_24" geometry={nodes.Curve025_24.geometry} material={materials['SVGMat.100']} />
          <mesh name="Curve025_25" geometry={nodes.Curve025_25.geometry} material={materials['SVGMat.101']} />
          <mesh name="Curve025_26" geometry={nodes.Curve025_26.geometry} material={materials['SVGMat.102']} />
          <mesh name="Curve025_27" geometry={nodes.Curve025_27.geometry} material={materials['SVGMat.103']} />
          <mesh name="Curve025_28" geometry={nodes.Curve025_28.geometry} material={materials['SVGMat.104']} />
          <mesh name="Curve025_29" geometry={nodes.Curve025_29.geometry} material={materials['SVGMat.105']} />
          <mesh name="Curve025_30" geometry={nodes.Curve025_30.geometry} material={materials['SVGMat.106']} />
          <mesh name="Curve025_31" geometry={nodes.Curve025_31.geometry} material={materials['SVGMat.108']} />
          <mesh name="Curve025_32" geometry={nodes.Curve025_32.geometry} material={materials['SVGMat.107']} />
          <mesh name="Curve025_33" geometry={nodes.Curve025_33.geometry} material={materials['SVGMat.086']} />
          <mesh name="Curve025_34" geometry={nodes.Curve025_34.geometry} material={materials['SVGMat.087']} />
          <mesh name="Curve025_35" geometry={nodes.Curve025_35.geometry} material={materials['SVGMat.088']} />
          <mesh name="Curve025_36" geometry={nodes.Curve025_36.geometry} material={materials['SVGMat.089']} />
          <mesh name="Curve025_37" geometry={nodes.Curve025_37.geometry} material={materials['SVGMat.091']} />
          <mesh name="Curve025_38" geometry={nodes.Curve025_38.geometry} material={materials['SVGMat.093']} />
          <mesh name="Curve025_39" geometry={nodes.Curve025_39.geometry} material={materials['SVGMat.098']} />
          <mesh name="Curve025_40" geometry={nodes.Curve025_40.geometry} material={materials['SVGMat.110']} />
          <mesh name="Curve025_41" geometry={nodes.Curve025_41.geometry} material={materials['SVGMat.111']} />
          <mesh name="Curve025_42" geometry={nodes.Curve025_42.geometry} material={materials['SVGMat.112']} />
          <mesh name="Curve025_43" geometry={nodes.Curve025_43.geometry} material={materials['SVGMat.090']} />
          <mesh name="Curve025_44" geometry={nodes.Curve025_44.geometry} material={materials['SVGMat.092']} />
          <mesh name="Curve025_45" geometry={nodes.Curve025_45.geometry} material={materials['SVGMat.094']} />
          <mesh name="Curve025_46" geometry={nodes.Curve025_46.geometry} material={materials['SVGMat.095']} />
          <mesh name="Curve025_47" geometry={nodes.Curve025_47.geometry} material={materials['SVGMat.109']} />
          <mesh name="Curve025_48" geometry={nodes.Curve025_48.geometry} material={materials['SVGMat.120']} />
          <mesh name="Curve025_49" geometry={nodes.Curve025_49.geometry} material={materials['SVGMat.122']} />
          <mesh name="Curve025_50" geometry={nodes.Curve025_50.geometry} material={materials['SVGMat.123']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/MLSC-Logo_alpha-final.glb')
